const teamLogos = {
    "Arizona Diamondbacks": "../assets/logos/ARI.svg",
    "Atlanta Braves": "../assets/logos/ATL.svg",
    "Baltimore Orioles": "../assets/logos/BAL.svg",
    "Boston Red Sox": "../assets/logos/BOS.svg",
    "Chicago Cubs": "../assets/logos/CHC.svg",
    "Chicago White Sox": "../assets/logos/CHW.svg",
    "Cincinnati Reds": "../assets/logos/CIN.svg",
    "Cleveland Guardians": "../assets/logos/CLE.svg",
    "Colorado Rockies": "../assets/logos/COL.svg",
    "Detroit Tigers": "../assets/logos/DET.svg",
    "Houston Astros": "../assets/logos/HOU.svg",
    "Kansas City Royals": "../assets/logos/KCR.svg",
    "Los Angeles Angels": "../assets/logos/LAA.svg",
    "Los Angeles Dodgers": "../assets/logos/LAD.svg",
    "Miami Marlins": "../assets/logos/MIA.svg",
    "Milwaukee Brewers": "../assets/logos/MIL.svg",
    "Minnesota Twins": "../assets/logos/MIN.svg",
    "New York Mets": "../assets/logos/NYM.svg",
    "New York Yankees": "../assets/logos/NYY.svg",
    "Oakland Athletics": "../assets/logos/OAK.svg",
    "Philadelphia Phillies": "../assets/logos/PHI.svg",
    "Pittsburgh Pirates": "../assets/logos/PIT.svg",
    "San Diego Padres": "../assets/logos/SDP.svg",
    "Seattle Mariners": "../assets/logos/SEA.svg",
    "San Francisco Giants": "../assets/logos/SFG.svg",
    "St. Louis Cardinals": "../assets/logos/STL.svg",
    "Tampa Bay Rays": "../assets/logos/TBR.svg",
    "Texas Rangers": "../assets/logos/TEX.svg",
    "Toronto Blue Jays": "../assets/logos/TOR.svg",
    "Washington Nationals": "../assets/logos/WSN.svg",
};

export default teamLogos;